import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Next Events",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased min-h-screen min-w-80 overflow-x-hidden">
        {children}
      </body>
    </html>
  );
}
